### ISSUE TITLE
Using a Buckler on a mount (horse in this case) will collide with and damage the mount.

### ISSUE THREAD

**Issue by cosmicgelatin** [seymourimadeit/Big-Brain#26] opened 2022-04-16 19:06 UTC
Considering that most of the time the rider can't target the mount, this feels like unintended behavior. Personally I think it'd be cool if mounted entities (living and vehicles) were given the velocity boost from the buckler when used.

**Comment by seymourimadeit** [comment] 2022-05-28 17:33
works as intended/wontfix

riptide tridents do the same thing

**Closed by seymourimadeit** 2022-05-28 17:33 UTC
